version: 2.1


workflows:
  main:
    jobs:
      - pylint:
          context:
            - docker-hub-creds



default_image: &default_image
  docker:
    - image: circleci/python:3.8
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD


default_dep_cache: &default_dep_cache
  - restore_cache:
      key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
  - run:
      name: Install Python deps in a venv
      command: |
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
  - save_cache:
      key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      paths:
        - "venv"



jobs:
  pylint:
    <<: *default_image
    steps:
      - checkout
      <<: *default_dep_cache
      - run: echo "this is the test"


