version: 2.1


workflows:
  main:
    jobs:
      - pylint:
          context:
            - docker-hub-creds


jobs:
  pylint:
    docker:
      - image: circleci/python:3.8
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "this is the test"


