version: 2.1


workflows:
  lint-and-test:
    jobs:
      - pylint-app:
          context:
            - docker-hub-creds
      - pylint-tests:
          context:
            - docker-hub-creds
      - unit-tests:
          context:
            - docker-hub-creds
            - alpaca-paper-creds



aliases:
  - &default_python_image
    docker:
      - image: circleci/python:3.8
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

  - &default_python_postgres_image
    docker:
      - image: circleci/python:3.8
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:12-ram
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: circleci-user
          POSTGRES_PASSWORD: circleci-password

  - &default_restore_cache
    restore_cache:
      key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

  - &default_install_deps
    run:
      name: Install Python deps in a venv
      command: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

  - &default_save_cache
    save_cache:
      key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      paths:
        - "venv"



jobs:
  pylint-app:
    <<: *default_python_image
    steps:
      - checkout
      - *default_restore_cache
      - *default_install_deps
      - *default_save_cache
      - run:
          name: Run pylint
          command: |
            . venv/bin/activate
            python -m pylint grand_trade_auto
  pylint-tests:
    <<: *default_python_image
    steps:
      - checkout
      - *default_restore_cache
      - *default_install_deps
      - *default_save_cache
      - run:
          name: Run pylint
          command: |
            . venv/bin/activate
            python -m pylint tests
  unit-tests:
    <<: *default_python_postgres_image
    steps:
      - checkout
      - *default_restore_cache
      - *default_install_deps
      - *default_save_cache
      - run:
          name: Setup mock files
          command: |
            mv .circleci/databases.conf.circleci config/databases.conf
            mv .circleci/.secrets.conf.circleci config/.secrets.conf
            mv .circleci/brokers.conf.circleci config/brokers.conf
            echo '\n[brokers :: circleci-alpaca-test]\n' >> config/.secrets.conf
            echo 'api key id : $APCA_API_KEY_ID\n'  >> config/.secrets.conf
            echo 'secret key : $APCA_API_SECRET_KEY\n' >> config/.secrets.conf
      - run:
          name: Run pytest unit tests
          command: |
            . venv/bin/activate
            pytest --cov-report=xml --cov=grand_trade_auto
      - run:
          name: Upload coverage results
          command: |
            . venv/bin/activate
            bash <(curl -s https://codecov.io/bash)
