version: 2.1

orbs:
  python: circleci/python@1.3.1
  ta-python: travelaudience/python@1.0.0

jobs:
  pylint:
    executor: python/default  # 3.8 default with 1.3.1 orb
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - ta-python/pylint

workflows:
  main:
    jobs:
      - pylint
